export * from './tiptap-editor'
export * from './tiptap-toolbar'
export { StarterKit } from '@tiptap/starter-kit'
export { Strike } from '@tiptap/extension-strike'
export { Underline } from '@tiptap/extension-underline'
export { Link } from '@tiptap/extension-link'
export { TextAlign } from '@tiptap/extension-text-align'
export { Image } from '@tiptap/extension-image'
export { ImageResize } from 'tiptap-extension-resize-image'
export { Placeholder } from '@tiptap/extension-placeholder'
