import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Header } from '@/features/layout/header'
import '@/shared/css/globals.css'

const inter = Inter({ subsets: ['latin'] })
// const spaceGrotesk = Space_Grotesk({
//     subsets: ['latin'],
//     weight: ['300', '400', '500', '600', '700'],
// })

export const metadata: Metadata = {
    title: 'Procewose',
    description: 'Generated by procewose',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <div className='flex flex-col w-full min-h-dvh'>
                    <div className='max-w-11xl w-full mx-auto flex flex-col flex-1'>
                        <Header />
                        {children}
                    </div>
                    <footer className='bg-neutral-600'>hello</footer>
                </div>
            </body>
        </html>
    )
}
