import type { Metadata } from 'next'
import { Inter, Space_Grotesk } from 'next/font/google'
import { Header } from '@/widgets/layout'
import '@/shared/css/globals.css'

const inter = Inter({ subsets: ['latin'] })
const spaceGrotesk = Space_Grotesk({
    subsets: ['latin'],
    weight: ['300', '400', '500', '600', '700'],
})

export const metadata: Metadata = {
    title: 'Procewose',
    description: 'Generated by procewose',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <div className='flex flex-col w-full min-h-dvh'>
                    <Header />
                    <section className='flex-1 flex flex-col w-full bg-blue-900'>
                        {children}
                    </section>
                </div>
            </body>
        </html>
    )
}
